import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Providers } from "./providers";

import "./globals.css";

import { Narbar } from "@/components/common/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "giigle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ overflow: "hidden" }}>
        <Providers>
          <div className="flex flex-col min-h-screen">
            <header>
              <Narbar />
            </header>
            <main className="bg-gray-100 flex-1 px-5 py-5 w-full">{children}</main>
            <footer className="bg-gray-800 text-white py-4 text-center">
              <p>&copy; {new Date().getFullYear()} giigle</p>
            </footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
