name: Deploy giigle-api to fly.io
on:
  push:
    branches:
      - main
    paths-ignore:
      - "frontend/**"
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: 
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            backend

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build
        run: |
          cd backend
          ./gradlew clean build -x test

      - uses: superfly/flyctl-actions/setup-flyctl@master
        name: Set up flyctl

      - name: Deploy
        run: |
          cd backend
          flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}