name: Deploy giigle-api to fly.io
on:
  push:
    branches:
      - main
    paths-ignore:
      - "frontend/**"
      - "*.md"
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: 
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            backend

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & Test
        run: |
          cd backend
          ./gradlew clean build

      - name: Upload Kover HTML report
        uses: actions/upload-artifact@v4
        with:
          name: kover-coverage-report
          path: backend/build/reports/kover/html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: backend/build/reports/kover/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
        name: Set up flyctl

      - name: Deploy
        run: |
          cd backend
          flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}